routes/web.php
<?php

use App\Http\Controllers\Auth\WelcomeController;
use App\Http\Controllers\Home\HomeController;
use App\Http\Controllers\Home\PanelHomeController;
use App\Http\Controllers\Home\StudentHomeController;
use App\Http\Controllers\Home\TutorialController;
use App\Http\Controllers\Panel\AnnouncementController;
use App\Http\Controllers\Panel\BadgeController;
use App\Http\Controllers\Panel\ChallengeController;
use App\Http\Controllers\Panel\GalleryController as PanelGalleryController;
use App\Http\Controllers\Panel\LiveLessonController;
use App\Http\Controllers\Panel\PenalizationController;
use App\Http\Controllers\Panel\QuestionController;
use App\Http\Controllers\Panel\QuestionOptionController;
use App\Http\Controllers\Panel\RewardController;
use App\Http\Controllers\Panel\RewardRedemptionStatusController;
use App\Http\Controllers\Panel\UserController;
use App\Http\Controllers\Portal\CommentController;
use App\Http\Controllers\Portal\GalleryController as PortalGalleryController;
use App\Http\Controllers\Portal\ProfileInformationController;
use App\Http\Controllers\Portal\RankingController;
use App\Http\Controllers\Portal\RewardRedemptionController;
use App\Http\Controllers\Portal\UserBadgesController;
use App\Http\Controllers\Portal\UserChallengeController;
use App\Http\Controllers\Portal\UserLiveLessonController;
use Illuminate\Support\Facades\Route;
use Spatie\WelcomeNotification\WelcomesNewUsers;
use App\Http\Controllers\Portal\NotificationEnrouteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web', WelcomesNewUsers::class]], function () {
    Route::get('welcome/{user}', [WelcomeController::class, 'showWelcomeForm'])->name('welcome');
    Route::post('welcome/{user}', [WelcomeController::class, 'savePassword']);
});

Route::middleware(['auth'])->group(function () {


    Route::get('', HomeController::class)->name('index');
    Route::view('/notification', 'modules.landing.notification.index');

    Route::get('challenges/{userChallenge}/{userChallengeAttempt}/score', [UserChallengeController::class, 'finishChallenge']);

    //RUTAS NOTIFICACIONES
    Route::get('/notification/read/{id}', [NotificationEnrouteController::class, 'read_notification'])->name('read_notification');

    Route::prefix('panel')->name('panel.')->middleware('can:is-administrator')->group(function () {
        Route::get('home_panel', PanelHomeController::class)->name('index');

        Route::middleware('verified')->group(function () {
            Route::controller(LiveLessonController::class)->prefix('live-lessons')->name('live-lessons.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::middleware('request.only.ajax')->group(function () {
                    Route::get('list', 'list')->name('list');
                    Route::post('', 'store')->name('store');
                    Route::get('{liveLesson}', 'show')->name('show');
                    Route::put('{liveLesson}', 'update')->name('update');
                    Route::delete('{liveLesson}', 'destroy')->name('destroy');
                });
            });

            Route::controller(ChallengeController::class)->prefix('challenges')->name('challenges.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::get('{challenge}', 'show')->name('show');

                Route::middleware('request.only.ajax')->group(function () {
                    Route::post('', 'store')->name('store');
                    Route::put('{challenge}', 'update')->name('update');
                    Route::delete('{challenge}', 'destroy')->name('destroy');
                    Route::put('{challenge}/publish', 'publish')->name('publish');
                    Route::put('{challenge}/move-to-draft', 'moveToDraft')->name('move_to_draft');

                    Route::controller(QuestionController::class)->prefix('{challenge}/questions')->name('questions.')->scopeBindings()->group(function () {
                        Route::get('', 'index')->name('index');
                        Route::post('', 'store')->name('store');
                        Route::get('{question}', 'show')->name('show');
                        Route::put('{question}', 'update')->name('update');
                        Route::delete('{question}', 'destroy')->name('destroy');

                        Route::controller(QuestionOptionController::class)->prefix('{question}/options')->name('options.')->scopeBindings()->group(function () {
                            Route::get('', 'index')->name('index');
                            Route::post('', 'store')->name('store');
                            Route::get('{option}', 'show')->name('show');
                            Route::put('{option}', 'update')->name('update');
                            Route::delete('{option}', 'destroy')->name('destroy');
                        });
                    });
                });
            });

            //RUTAS USER
            Route::controller(UserController::class)->prefix('users')->name('users.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::middleware('request.only.ajax')->group(function () {
                    Route::get('list', [UserController::class, 'list'])->name('list');
                    Route::post('', 'store')->name('store');
                    Route::get('{user}', 'show')->name('show');
                    Route::put('{user}', 'update')->name('update');
                });
            });

            //RUTAS GIFT
            Route::controller(RewardController::class)->prefix('rewards')->name('rewards.')->group(function () {
                Route::get('', 'index')->name('all');
                Route::post('', 'store')->name('store');

                Route::controller(RewardRedemptionStatusController::class)->prefix('redemption-status')->name('redemption-status.')->group(function () {
                    Route::get('', 'index')->name('index');
                    Route::get('list', 'list')->name('list');
                    Route::get('{rewardRedemption}', 'show')->name('show');
                    Route::patch('{rewardRedemption}', 'update')->name('patch');
                });
                Route::view('create', 'panel.rewards.create')->name('create');
                Route::get('{reward}/edit', 'edit')->name('edit');
                Route::put('{reward}', 'update')->name('update');
                Route::delete('{reward}', 'destroy')->name('destroy');
            });

            Route::controller(PanelGalleryController::class)->prefix('gallery')->name('gallery.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::middleware('request.only.ajax')->group(function () {
                    Route::post('', 'store')->name('store');
                    Route::get('list', 'list')->name('list');
                    Route::get('{gallery}', 'show')->name('show');
                    Route::put('{gallery}', 'update')->name('update');
                });
            });

            Route::controller(PenalizationController::class)->prefix('penalizations')->name('penalizations.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::post('{user}', 'store')->name('store')->middleware('request.only.ajax');
            });

            Route::controller(AnnouncementController::class)->prefix('announcements')->name('announcements.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::middleware('request.only.ajax')->group(function () {
                    Route::post('', 'store')->name('store');
                    Route::delete('', 'destroy')->name('destroy');
                });
            });

            Route::controller(BadgeController::class)->prefix('badges')->name('badges.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::middleware('request.only.ajax')->group(function () {
                    Route::get('list', 'list')->name('list');
                    Route::post('', 'store')->name('store');
                    Route::get('{badge}', 'show')->name('show');
                    Route::put('{badge}', 'update')->name('update');
                });
            });

            //RUTAS OTHER
            Route::view('other/tutorial', 'panel.other.tutorial')->name('other.tutorial');

            //RUTAS PROFILE
            Route::view('profile', 'panel.profile.index')->name('profile.index');

            //RUTAS CONFIG
            Route::view('config', 'panel.config.index')->name('config.index');
        });
    });

    Route::middleware('can:is-student')->group(function () {
        Route::prefix('tutorial')->name('tutorial.')->controller(TutorialController::class)->group(function () {
            Route::get('', 'index')->name('index');
            Route::post('', 'finishTutorial')->name('finish');
        });

        Route::middleware('tutorial')->group(function () {
            Route::get('home', StudentHomeController::class)->name('portal.index');

            //RUTAS PROFILE
            Route::controller(ProfileInformationController::class)->prefix('profile')->name('profile.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::post('avatar', 'updateProfileImage')->name('image.update');
            });

            Route::middleware('verified')->group(function () {
                //RUTAS LIVE

app/Http/Controllers/Home/HomeController.php
<?php

namespace App\Http\Controllers\Home;

use App\Enums\UserTypes;
use App\Http\Controllers\Controller;

class HomeController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function __invoke()
    {
        /** @var \App\Models\User */
        $user = auth()->user();

        $redirect = $user->user_type == UserTypes::student->value ? 'portal.index' : 'panel.index';

        return redirect()->route($redirect);
    }
}

app/Http/Controllers/Home/PanelHomeController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;

class PanelHomeController extends Controller
{
    /**
     * Handle the incoming request.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function __invoke()
    {
        return view('panel.home.index');
    }
}

app/Http/Controllers/Home/StudentHomeController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;
use App\Services\AnnouncementService;

class StudentHomeController extends Controller
{
    /** @var AnnouncementService */
    private $announcementService;

    /**
     * Create a new controller instance.
     *
     * @param  AnnouncementService  $announcementService
     * @return void
     */
    public function __construct(AnnouncementService $announcementService)
    {
        $this->announcementService = $announcementService;
    }

    /**
     * Handle the incoming request.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function __invoke()
    {
        $files = $this->announcementService->list();

        return view('modules.landing.home.index', compact('files'));
    }
}

app/Http/Controllers/Home/TutorialController.php
<?php

namespace App\Http\Controllers\Home;

use App\Http\Controllers\Controller;

class TutorialController extends Controller
{
    /**
     * Muestra la vista del tutorial.
     *
     * @return \Illuminate\Contracts\View\View
     */
    public function index()
    {
        return view('modules.landing.tutorial.index');
    }

    /**
     * Actualiza la fecha de finalización del tutorial.
     *
     * @return \Illuminate\Http\RedirectResponse
     */
    public function finishTutorial()
    {
        /** @var \App\Models\User */
        $user = auth()->user();
        if ($user->tutorial_finished_at === null) {
            $user->tutorial_finished_at = now();
            $user->save();
        }

        return redirect()->route('portal.index');
    }
}

resources/views/modules/landing/home/index.blade.php
@extends('layouts.app')
@section('content')

   

    <div class="row-reverse">
        <div class="col">
            <div class="row-reverse">
                <div class="col p-0">
                    <label for="" class="h3">BIENVENIDO A <span class="font-weight-bold">LENOVO SCHOOL</span></label>
                </div>
                <div class="col p-0">
                    @if ($files->count() > 0)
                        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel" style="z-index: 1 !important;">
                            <ol class="carousel-indicators">
                                @foreach ($files as $file)
                                    <li data-target="#carouselExampleIndicators" data-slide-to="{{ $loop->index }}" class="@if ($loop->first) active @endif"></li>
                                @endforeach
                            </ol>
                            <div class="carousel-inner">
                                @foreach ($files as $file)
                                    <div class="carousel-item @if ($loop->first) active @endif">
                                        <img class="d-block w-100" src="{{ $file }}" alt="First slide">
                                    </div>
                                @endforeach
                            </div>
                            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                                <span class="sr-only">Previous</span>
                            </a>
                            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                                <span class="sr-only">Next</span>
                            </a>
                        </div>
                    @endif
                </div>
            </div>
        </div>

        <div class="col">
            <div class="row">
                <div class="col-4">
                    <div class="card" id="class_card" onclick="window.location='{{ route('live-lessons.index') }}'">
                        <div class="card-body d-flex align-items-end justify-content-center text-center">
                            <div class="row-reverse">
                                <div class="col">
                                    <label for="" class="h3 text-white font-weight-bold">Clases en vivo</label>
                                </div>
                                <div class="col">
                                    <label for="" class="text-white">Entrena tus habilidades</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card" id="challenge_card" onclick="window.location='{{ route('challenges.index') }}'">
                        <div class="card-body d-flex align-items-end justify-content-center text-center">
                            <div class="row-reverse">
                                <div class="col">
                                    <label for="" class="h3 text-white font-weight-bold">Desafios Lenovo</label>
                                </div>
                                <div class="col">
                                    <label for="" class="text-white">Prueba tus conocimientos</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-4">
                    <div class="card" id="gallery_card" onclick="window.location='{{ route('gallery.index') }}'">
                        <div class="card-body d-flex align-items-end justify-content-center text-center">
                            <div class="row-reverse">
                                <div class="col">
                                    <label for="" class="h3 text-white font-weight-bold">Galería</label>
                                </div>
                                <div class="col">
                                    <label for="" class="text-white">Refresca tus aprendizajes</label>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <style>
        #class_card {
            transition: transform .2s;
            cursor: pointer;
            border-radius: 20px;
            min-height: 55vh;
            max-height: 55vh;
            background: url('/assets/img/class.png');
            background-size: cover
        }

        #class_card:hover {
            transform: scale(1.05);
            border: solid 2px #7DBE38;
        }

        #challenge_card {
            transition: transform .2s;
            cursor: pointer;
            border-radius: 20px;
            min-height: 55vh;
            max-height: 55vh;
            background: url('/assets/img/challenge.png');
            background-size: cover
        }

        #challenge_card:hover {
            transform: scale(1.05);
            border: solid 2px #7DBE38;
        }

        #gallery_card {
            transition: transform .2s;
            cursor: pointer;
            border-radius: 20px;
            min-height: 55vh;
            max-height: 55vh;
            background: url('/assets/img/gallery.png');
            background-size: cover
        }

        #gallery_card:hover {
            transform: scale(1.05);
            border: solid 2px #7DBE38;
        }
    </style>


@endsection