routes/web.php
<?php

use App\Http\Controllers\Auth\WelcomeController;
use App\Http\Controllers\Home\HomeController;
use App\Http\Controllers\Home\PanelHomeController;
use App\Http\Controllers\Home\StudentHomeController;
use App\Http\Controllers\Home\TutorialController;
use App\Http\Controllers\Panel\AnnouncementController;
use App\Http\Controllers\Panel\BadgeController;
use App\Http\Controllers\Panel\ChallengeController;
use App\Http\Controllers\Panel\GalleryController as PanelGalleryController;
use App\Http\Controllers\Panel\LiveLessonController;
use App\Http\Controllers\Panel\PenalizationController;
use App\Http\Controllers\Panel\QuestionController;
use App\Http\Controllers\Panel\QuestionOptionController;
use App\Http\Controllers\Panel\RewardController;
use App\Http\Controllers\Panel\RewardRedemptionStatusController;
use App\Http\Controllers\Panel\UserController;
use App\Http\Controllers\Portal\CommentController;
use App\Http\Controllers\Portal\GalleryController as PortalGalleryController;
use App\Http\Controllers\Portal\ProfileInformationController;
use App\Http\Controllers\Portal\RankingController;
use App\Http\Controllers\Portal\RewardRedemptionController;
use App\Http\Controllers\Portal\UserBadgesController;
use App\Http\Controllers\Portal\UserChallengeController;
use App\Http\Controllers\Portal\UserLiveLessonController;
use Illuminate\Support\Facades\Route;
use Spatie\WelcomeNotification\WelcomesNewUsers;
use App\Http\Controllers\Portal\NotificationEnrouteController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => ['web', WelcomesNewUsers::class]], function () {
    Route::get('welcome/{user}', [WelcomeController::class, 'showWelcomeForm'])->name('welcome');
    Route::post('welcome/{user}', [WelcomeController::class, 'savePassword']);
});

Route::middleware(['auth'])->group(function () {


    Route::get('', HomeController::class)->name('index');
    Route::view('/notification', 'modules.landing.notification.index');

    Route::get('challenges/{userChallenge}/{userChallengeAttempt}/score', [UserChallengeController::class, 'finishChallenge']);

    //RUTAS NOTIFICACIONES
    Route::get('/notification/read/{id}', [NotificationEnrouteController::class, 'read_notification'])->name('read_notification');

    Route::prefix('panel')->name('panel.')->middleware('can:is-administrator')->group(function () {
        Route::get('home_panel', PanelHomeController::class)->name('index');

        Route::middleware('verified')->group(function () {
            Route::controller(LiveLessonController::class)->prefix('live-lessons')->name('live-lessons.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::middleware('request.only.ajax')->group(function () {
                    Route::get('list', 'list')->name('list');
                    Route::post('', 'store')->name('store');
                    Route::get('{liveLesson}', 'show')->name('show');
                    Route::put('{liveLesson}', 'update')->name('update');
                    Route::delete('{liveLesson}', 'destroy')->name('destroy');
                });
            });

            Route::controller(ChallengeController::class)->prefix('challenges')->name('challenges.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::get('{challenge}', 'show')->name('show');

                Route::middleware('request.only.ajax')->group(function () {
                    Route::post('', 'store')->name('store');
                    Route::put('{challenge}', 'update')->name('update');
                    Route::delete('{challenge}', 'destroy')->name('destroy');
                    Route::put('{challenge}/publish', 'publish')->name('publish');
                    Route::put('{challenge}/move-to-draft', 'moveToDraft')->name('move_to_draft');

                    Route::controller(QuestionController::class)->prefix('{challenge}/questions')->name('questions.')->scopeBindings()->group(function () {
                        Route::get('', 'index')->name('index');
                        Route::post('', 'store')->name('store');
                        Route::get('{question}', 'show')->name('show');
                        Route::put('{question}', 'update')->name('update');
                        Route::delete('{question}', 'destroy')->name('destroy');

                        Route::controller(QuestionOptionController::class)->prefix('{question}/options')->name('options.')->scopeBindings()->group(function () {
                            Route::get('', 'index')->name('index');
                            Route::post('', 'store')->name('store');
                            Route::get('{option}', 'show')->name('show');
                            Route::put('{option}', 'update')->name('update');
                            Route::delete('{option}', 'destroy')->name('destroy');
                        });
                    });
                });
            });

            //RUTAS USER
            Route::controller(UserController::class)->prefix('users')->name('users.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::middleware('request.only.ajax')->group(function () {
                    Route::get('list', [UserController::class, 'list'])->name('list');
                    Route::post('', 'store')->name('store');
                    Route::get('{user}', 'show')->name('show');
                    Route::put('{user}', 'update')->name('update');
                });
            });

            //RUTAS GIFT
            Route::controller(RewardController::class)->prefix('rewards')->name('rewards.')->group(function () {
                Route::get('', 'index')->name('all');
                Route::post('', 'store')->name('store');

                Route::controller(RewardRedemptionStatusController::class)->prefix('redemption-status')->name('redemption-status.')->group(function () {
                    Route::get('', 'index')->name('index');
                    Route::get('list', 'list')->name('list');
                    Route::get('{rewardRedemption}', 'show')->name('show');
                    Route::patch('{rewardRedemption}', 'update')->name('patch');
                });
                Route::view('create', 'panel.rewards.create')->name('create');
                Route::get('{reward}/edit', 'edit')->name('edit');
                Route::put('{reward}', 'update')->name('update');
                Route::delete('{reward}', 'destroy')->name('destroy');
            });

            Route::controller(PanelGalleryController::class)->prefix('gallery')->name('gallery.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::middleware('request.only.ajax')->group(function () {
                    Route::post('', 'store')->name('store');
                    Route::get('list', 'list')->name('list');
                    Route::get('{gallery}', 'show')->name('show');
                    Route::put('{gallery}', 'update')->name('update');
                });
            });

            Route::controller(PenalizationController::class)->prefix('penalizations')->name('penalizations.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::post('{user}', 'store')->name('store')->middleware('request.only.ajax');
            });

            Route::controller(AnnouncementController::class)->prefix('announcements')->name('announcements.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::middleware('request.only.ajax')->group(function () {
                    Route::post('', 'store')->name('store');
                    Route::delete('', 'destroy')->name('destroy');
                });
            });

            Route::controller(BadgeController::class)->prefix('badges')->name('badges.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::middleware('request.only.ajax')->group(function () {
                    Route::get('list', 'list')->name('list');
                    Route::post('', 'store')->name('store');
                    Route::get('{badge}', 'show')->name('show');
                    Route::put('{badge}', 'update')->name('update');
                });
            });

            //RUTAS OTHER
            Route::view('other/tutorial', 'panel.other.tutorial')->name('other.tutorial');

            //RUTAS PROFILE
            Route::view('profile', 'panel.profile.index')->name('profile.index');

            //RUTAS CONFIG
            Route::view('config', 'panel.config.index')->name('config.index');
        });
    });

    Route::middleware('can:is-student')->group(function () {
        Route::prefix('tutorial')->name('tutorial.')->controller(TutorialController::class)->group(function () {
            Route::get('', 'index')->name('index');
            Route::post('', 'finishTutorial')->name('finish');
        });

        Route::middleware('tutorial')->group(function () {
            Route::get('home', StudentHomeController::class)->name('portal.index');

            //RUTAS PROFILE
            Route::controller(ProfileInformationController::class)->prefix('profile')->name('profile.')->group(function () {
                Route::get('', 'index')->name('index');
                Route::post('avatar', 'updateProfileImage')->name('image.update');
            });

            Route::middleware('verified')->group(function () {
                //RUTAS LIVE

resources/views/panel/layouts/content/components/end.blade.php
<script src="{{ mix('js/manifest.js') }}"></script>
<script src="{{ mix('js/vendor.js') }}"></script>
<script src="{{ asset('/other/panel/js/app.js') }}"></script>
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>

<!-- datatables JS -->
<script src="https://cdn.datatables.net/1.10.13/js/jquery.dataTables.min.js" defer></script>
<script type="text/javascript" src="{{ asset('/other/panel/datatable/datatables/datatables.min.js') }}" defer></script>

<!-- para usar botones en datatables JS -->
<script src="{{ asset('/other/panel/datatable/datatables/Buttons-1.5.6/js/dataTables.buttons.min.js') }}" defer></script>
<script src="{{ asset('/other/panel/datatable/datatables/JSZip-2.5.0/jszip.min.js') }}" defer></script>
<script src="{{ asset('/other/panel/datatable/datatables/pdfmake-0.1.36/pdfmake.min.js') }}" defer></script>
<script src="{{ asset('/other/panel/datatable/datatables/pdfmake-0.1.36/vfs_fonts.js') }}" defer></script>
<script src="{{ asset('/other/panel/datatable/datatables/Buttons-1.5.6/js/buttons.html5.min.js') }}" defer></script>
@stack('scripts')

<!-- código JS propìo-->
{{-- <script type="text/javascript" src="{{ asset('/other/panel/datatable/main.js') }}"></script> --}}


<style>
    table thead {
        background: #25353f;
        color: white;
    }

    div.dataTables_wrapper div.dataTables_filter input {
        background: #e1e1e1;
    }
</style>

<script>
    if (document.getElementById("chart-bars") !== null) {
        var ctx = document.getElementById("chart-bars").getContext("2d");

        new Chart(ctx, {
            type: "bar",
            data: {
                labels: ["M", "T", "W", "T", "F", "S", "S"],
                datasets: [{
                    label: "Sales",
                    tension: 0.4,
                    borderWidth: 0,
                    borderRadius: 4,
                    borderSkipped: false,
                    backgroundColor: "rgba(255, 255, 255, .8)",
                    data: [50, 20, 10, 22, 50, 10, 40],
                    maxBarThickness: 6
                }, ],
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: false,
                    }
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    y: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5],
                            color: 'rgba(255, 255, 255, .2)'
                        },
                        ticks: {
                            suggestedMin: 0,
                            suggestedMax: 500,
                            beginAtZero: true,
                            padding: 10,
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                            color: "#fff"
                        },
                    },
                    x: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5],
                            color: 'rgba(255, 255, 255, .2)'
                        },
                        ticks: {
                            display: true,
                            color: '#f8f9fa',
                            padding: 10,
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                },
            },
        });
    }


    if (document.getElementById("chart-line") != null) {
        var ctx2 = document.getElementById("chart-line").getContext("2d");

        new Chart(ctx2, {
            type: "line",
            data: {
                labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                datasets: [{
                    label: "Mobile apps",
                    tension: 0,
                    borderWidth: 0,
                    pointRadius: 5,
                    pointBackgroundColor: "rgba(255, 255, 255, .8)",
                    pointBorderColor: "transparent",
                    borderColor: "rgba(255, 255, 255, .8)",
                    borderColor: "rgba(255, 255, 255, .8)",
                    borderWidth: 4,
                    backgroundColor: "transparent",
                    fill: true,
                    data: [50, 40, 300, 320, 500, 350, 200, 230, 500],
                    maxBarThickness: 6

                }],
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: false,
                    }
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    y: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5],
                            color: 'rgba(255, 255, 255, .2)'
                        },
                        ticks: {
                            display: true,
                            color: '#f8f9fa',
                            padding: 10,
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                    x: {
                        grid: {
                            drawBorder: false,
                            display: false,
                            drawOnChartArea: false,
                            drawTicks: false,
                            borderDash: [5, 5]
                        },
                        ticks: {
                            display: true,
                            color: '#f8f9fa',
                            padding: 10,
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                },
            },
        });
    }

    if (document.getElementById("chart-line-tasks") != null) {
        var ctx3 = document.getElementById("chart-line-tasks").getContext("2d");

        new Chart(ctx3, {
            type: "line",
            data: {
                labels: ["Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
                datasets: [{
                    label: "Mobile apps",
                    tension: 0,
                    borderWidth: 0,
                    pointRadius: 5,
                    pointBackgroundColor: "rgba(255, 255, 255, .8)",
                    pointBorderColor: "transparent",
                    borderColor: "rgba(255, 255, 255, .8)",
                    borderWidth: 4,
                    backgroundColor: "transparent",
                    fill: true,
                    data: [50, 40, 300, 220, 500, 250, 400, 230, 500],
                    maxBarThickness: 6

                }],
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: {
                        display: false,
                    }
                },
                interaction: {
                    intersect: false,
                    mode: 'index',
                },
                scales: {
                    y: {
                        grid: {
                            drawBorder: false,
                            display: true,
                            drawOnChartArea: true,
                            drawTicks: false,
                            borderDash: [5, 5],
                            color: 'rgba(255, 255, 255, .2)'
                        },
                        ticks: {
                            display: true,
                            padding: 10,
                            color: '#f8f9fa',
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                    x: {
                        grid: {
                            drawBorder: false,
                            display: false,
                            drawOnChartArea: false,
                            drawTicks: false,
                            borderDash: [5, 5]
                        },
                        ticks: {
                            display: true,
                            color: '#f8f9fa',
                            padding: 10,
                            font: {
                                size: 14,
                                weight: 300,
                                family: "Roboto",
                                style: 'normal',
                                lineHeight: 2
                            },
                        }
                    },
                },
            },
        });
    }
</script>
<script>
    var win = navigator.platform.indexOf('Win') > -1;
    if (win && document.querySelector('#sidenav-scrollbar')) {
        var options = {
            damping: '0.5'
        }
        Scrollbar.init(document.querySelector('#sidenav-scrollbar'), options);
    }
</script>
<!-- Github buttons -->
<script async defer src="https://buttons.github.io/buttons.js"></script>
</body>

</html>

resources/views/panel/layouts/content/components/footer.blade.php
      <!-- <footer class="footer py-4">
        <div class="container-fluid">
          <div class="row align-items-center justify-content-lg-between">
            <div class="col mb-lg-0 mb-4">
              <div class="copyright text-center text-sm text-muted text-lg-start d-flex justify-content-center">
                © <script>
                  document.write(new Date().getFullYear())
                </script>
                <a href="https://www.creative-tim.com" class="font-weight-bold mx-2" target="_blank">People by Overall</a>
              </div>
            </div>
            
          </div>
        </div>
      </footer>

resources/views/panel/layouts/content/components/sidebar.blade.php
<aside class="sidenav navbar navbar-vertical navbar-expand-xs border-0 border-radius-xl my-3 fixed-start ms-3" id="sidenav-main" style="background: #25353f !important;">
    <div class="sidenav-header">
        <i class="fas fa-times p-3 cursor-pointer text-white opacity-5 position-absolute end-0 top-0 d-none d-xl-none" aria-hidden="true" id="iconSidenav"></i>
        <a class="navbar-brand m-0 d-flex justify-content-center" href="{{ route('panel.index') }}" target="_blank">
            <img src="{{ asset('/other/panel/img/logo_blanco.png') }}" class="navbar-brand-img h-100 mx-auto" alt="main_logo">
        </a>
    </div>
    <hr class="horizontal light mt-0 mb-2">
    <div class="collapse navbar-collapse  w-auto  max-height-vh-100" style="min-height:67%" id="sidenav-collapse-main">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link text-white  {{ request()->is('home') ? 'active' : '' }}" href="{{ route('panel.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">dashboard</i>
                    </div>
                    <span class="nav-link-text ms-1">Inicio</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->is('panel/users') ? 'active' : '' }}" href="{{ route('panel.users.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">group</i>
                    </div>
                    <span class="nav-link-text ms-1">Usuarios</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->is('panel/challenges') ? 'active' : '' }}" href="{{ route('panel.challenges.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">receipt_long</i>
                    </div>
                    <span class="nav-link-text ms-1">Desafíos</span>
                </a>
            </li>
            <li class="nav-item">
                @php
                    $routeIsRewards = request()->is('panel/rewards', 'panel/rewards/*');
                @endphp
                <a class="nav-link text-white {{ $routeIsRewards ? 'active' : 'collapsed' }}" data-bs-toggle="collapse" aria-expanded="{{ $routeIsRewards ? 'true' : 'false' }}" href="#profileExample3">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">receipt_long</i>
                    </div>
                    <span class="nav-link-text ms-1">Premios</span>
                </a>
                <div class="collapse {{ $routeIsRewards ? 'show' : '' }}" id="profileExample3">
                    <ul class="nav nav-sm flex-column">
                        <li class="nav-item">
                            <a class="nav-link text-white {{ request()->is('panel/rewards/create') ? 'active' : '' }}" href="{{ route('panel.rewards.create') }}">
                                <span class="sidenav-mini-icon"> P </span>
                                <span class="sidenav-normal  ms-2  ps-1">Crear premios</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white {{ request()->is('panel/rewards/redemption-status') ? 'active' : '' }}" href="{{ route('panel.rewards.redemption-status.index') }}">
                                <span class="sidenav-mini-icon"> P </span>
                                <span class="sidenav-normal  ms-2  ps-1">Seguimiento de premios</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white {{ request()->is('panel/rewards') ? 'active' : '' }}" href="{{ route('panel.rewards.all') }}">
                                <span class="sidenav-mini-icon"> A </span>
                                <span class="sidenav-normal  ms-2  ps-1">Ver todos los premios</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->is('panel/live-lessons') ? 'active' : '' }}" href="{{ route('panel.live-lessons.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">receipt_long</i>
                    </div>
                    <span class="nav-link-text ms-1">Clases en vivo</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->is('panel/gallery') ? 'active' : '' }}" href="{{ route('panel.gallery.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">collections_bookmark</i>
                    </div>
                    <span class="nav-link-text ms-1">Galería</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->is('panel/penalizations') ? 'active' : '' }}" href="{{ route('panel.penalizations.index') }} ">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">receipt_long</i>
                    </div>
                    <span class="nav-link-text ms-1">Penalizaciones</span>
                </a>
            </li>
            <li class="nav-item">
                @php
                    $routeIsContents = request()->is('panel/announcements', 'panel/badges', 'other/tutorial');
                @endphp
                <a class="nav-link text-white {{ $routeIsContents ? 'active' : 'collapsed' }}" data-bs-toggle="collapse" aria-expanded="{{ $routeIsContents ? 'true' : 'false' }}" href="#profileExample5">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">receipt_long</i>
                    </div>
                    <span class="nav-link-text ms-1">Contenidos</span>
                </a>
                <div class="collapse {{ $routeIsContents ? 'show' : '' }}" id="profileExample5">
                    <ul class="nav nav-sm flex-column">
                        <li class="nav-item">
                            <a class="nav-link text-white {{ request()->is('panel/announcements') ? 'active' : '' }}" href="{{ route('panel.announcements.index') }}">
                                <span class="sidenav-mini-icon"> P </span>
                                <span class="sidenav-normal  ms-2  ps-1">Anuncios</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white {{ request()->is('panel/badges') ? 'active' : '' }}" href="{{ route('panel.badges.index') }}">
                                <span class="sidenav-mini-icon"> P </span>
                                <span class="sidenav-normal  ms-2  ps-1">Insignias</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white {{ request()->is('other/tutorial') ? 'active' : '' }}" href="{{ route('panel.other.tutorial') }}">
                                <span class="sidenav-mini-icon"> P </span>
                                <span class="sidenav-normal  ms-2  ps-1">Tutoriales</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class="nav-item mt-3">
                <h6 class="ps-4 ms-2 text-uppercase text-xs text-white font-weight-bolder opacity-8">Otras configuraciones</h6>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white {{ request()->is('profile') ? 'active' : '' }}" href="{{ route('panel.profile.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">person</i>
                    </div>
                    <span class="nav-link-text ms-1">Mi perfil</span>
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-link text-white {{ request()->is('config') ? 'active' : '' }}" href="{{ route('panel.config.index') }}">
                    <div class="text-white text-center me-2 d-flex align-items-center justify-content-center">
                        <i class="material-icons opacity-10">assignment</i>
                    </div>
                    <span class="nav-link-text ms-1">Configuracion de cuenta</span>
                </a>
            </li>
        </ul>
    </div>
    <div class="sidenav-footer position-absolute w-100 bottom-0">
        <div class="mx-3">
            <form action="{{ route('logout') }}" method="post">
                @csrf
                <button type="submit" class="btn bg-gradient-danger mt-4 w-100">Cerrar Sesión</button>
            </form>
        </div>
    </div>
</aside>